services:
  mysql:
    image: mysql:8.0
    container_name: sitwallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sitwallet
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: sitwallet-backend
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 5000
      CORS_ORIGIN: http://localhost:8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: sitwallet
      JWT_SECRET: 4197831a39e91d61d532682f41494d1bc1d5a2e34b333ec4e632a97fa5021d6e
      APP_ENCRYPTION_KEY: 971be696c9a1e6cfe7914f107c846fe4d9664459113a7d28834fdfe93ce9c521
      COOKIE_SECURE: "false"
      CSRF_ENABLED: "true"
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: sitwallet-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data: